###GET ALL
GET http://localhost:8080/api/usuario


### post

POST http://localhost:8080/api/usuario
Content-Type: application/json

{    
    "email": "asd@asd",
    "contraseña": "asd",
    "tipo": "admin",
    "nombre": "asd",
    "apellido": "asd"
}

### login

POST http://localhost:8080/api/usuario/login
Content-Type: application/json

{
    "email": "asd@asd",
    "contraseña": "asd"
}

### login

POST http://localhost:8080/api/usuario/login
Content-Type: application/json

{
    "email": "cliente@cliente",
    "contraseña": "asd"
}