###GET ALL
GET http://localhost:8080/api/turno

### GET BY ID
GET http://localhost:8080/api/turno/1

### POST
POST http://localhost:8080/api/turno
Content-Type: application/json

{
    "id": "2",
    "fecyhora": "2024 06 11 16:30:00Z",
    "precio": "240.3",
    "entrega": "120.15",
    "descripcion": "carie",
    "pieza": "1.1"
}

### PUT
PUT http://localhost:8080/api/turno/2
Content-Type: application/json

{
    "id": "2",
    "fecyhora": "2024 06 12 15:00:00Z",
    "precio": "500",
    "entrega": "220.5",
    "descripcion": "conducto",
    "pieza": "2.2"
}

### PATCH
PATCH http://localhost:8080/api/turno/2
Content-Type: application/json

{
    "id": "2",
    "fecyhora": "2024 06 13 18:30:00Z",
    "precio": "700",
    "entrega": "350",
    "descripcion": "restauracion",
    "pieza": "3.3"
}

### DELETE
DELETE http://localhost:8080/api/turno/2