###GET ALL
GET http://localhost:8080/api/paciente

### GET BY ID
GET http://localhost:8080/api/paciente/1

### POST
POST http://localhost:8080/api/paciente
Content-Type: application/json

{
    "nombre": "Mariela",
    "apellido": "Gomez",
    "genero":"Femenino",
    "direccion":"Calle falsa 456",
    "telefono":"4330033",
    "email":"mariela@gmail.com.ar"
}

### PUT
PUT http://localhost:8080/api/paciente/2
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "Langosta",
    "genero":"Masculino",
    "direccion":"Calle falsa 123",
    "telefono":"123456789",
    "email":"correo@gmail.com.ar"
}

### PATCH
PATCH http://localhost:8080/api/paciente/456
Content-Type: application/json

{
    "dni": "456",
    "nombre": "Juan",
    "apellido": "Mandioca",
    "genero":"Masculino",
    "direccion":"Calle falsa 123",
    "telefono":"123456789",
    "email":"correo@gmail.com.ar"
}

### DELETE
DELETE http://localhost:8080/api/paciente/2

