### GET ALL
Get http://localhost:8080/api/tipoImagen

### POST CHARACTER TO DELETE
# @name createtipoImagenToDelete
POST http://localhost:8080/api/tipoImagen
Content-Type: application/json

{
    "nombre": "Resonancia Magnetica16"
}

### ID
@id = {{}}

### GET ONE
GET http://localhost:8080/api/tipoImagen/{{idToDelete}}

### PUT
PUT http://localhost:8080/api/tipoImagen/{{id}}
Content-Type: application/json

{
    "nombre": "Resonancia Magnetica6"
}

### DELETE
@idToDelete = {{createtipoImagenToDelete.response.body.data.id}}
DELETE http://localhost:8080/api/tipoImagen/{{idToDelete}}